### ISSUE TITLE
bundle format doesn't support dictionary constraints

### ISSUE THREAD

**Issue by mitechie** [juju/bundlechanges#7]
Reference to: https://bugs.launchpad.net/juju-quickstart/+bug/1478254

juju quickstart http://cloud-benchmarks.org/submissions/19.yaml
usage: juju-quickstart [-h] [-e ENV_NAME] [-n BUNDLE_NAME] [-i] [-u]
                       [--gui-charm-url CHARM_URL] [--gui-port PORT]
                       [--no-browser] [--environments-file ENV_FILE]
                       [--distro-only] [--ppa] [--version] [--debug]
                       [--description] [--upload-tools]
                       [--upload-series UPLOAD_SERIES]
                       [--constraints CONSTRAINTS]
                       [BUNDLE]
juju-quickstart: error: unable to open the bundle: invalid bundle data:
  service mongodb has invalid constraints {u'mem': u'1700M', u'arch': u'amd64', u'cpu-power': u'138', u'cpu-cores': u'1', u'root-disk': u'10240M'}
ERROR subprocess encountered error code 2

This was a different bundle. It appears that if constraints are not a string (instead a dictionary) quickstart will fail. Deployer has support for constraints as dictionaries. While this isn't explicitly in the bundle format, it'd be great to see this become official. Treating constraints as a dictionary means better parsing and management of bundles as well as ease in writing bundles by hand.

http://bazaar.launchpad.net/~juju-deployers/juju-deployer/trunk/view/head:/deployer/env/base.py#L88

**Comment by frankban** [comment]
I am closing this as now bundlechanges handles constraints the same way as Juju does, and also this request was more related to jujubundlelib, which is becoming less and less relevant.
